package asr

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/coder/websocket"
)

// frames are testdata/doubao-frames.json: frames generated by a script from
// the protocol, in the plan endpoint's wire format — a request, two audio heads, the replies to one
// clip, and an error frame.
type frames struct {
	Request    string   `json:"request"`
	AudioHeads []string `json:"audio_heads"`
	Server     []string `json:"server"`
	Error      string   `json:"error"`
}

func loadFrames(t *testing.T) frames {
	t.Helper()
	b, err := os.ReadFile("testdata/doubao-frames.json")
	if err != nil {
		t.Fatal(err)
	}
	var f frames
	if err := json.Unmarshal(b, &f); err != nil {
		t.Fatal(err)
	}
	return f
}

func unhex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func gunzip(t *testing.T, b []byte) []byte {
	t.Helper()
	zr, err := gzip.NewReader(bytes.NewReader(b))
	if err != nil {
		t.Fatal(err)
	}
	out, err := io.ReadAll(zr)
	if err != nil {
		t.Fatal(err)
	}
	return out
}

// TestDoubaoFrame: frame lays out header, sequence and size as the fixture
// does, and its payload gunzips back to the input; the compressed bytes are
// not compared, since two gzip encoders may disagree on them.
func TestDoubaoFrame(t *testing.T) {
	f := loadFrames(t)
	want := unhex(t, f.Request)
	payload := gunzip(t, want[12:])
	got := frame(msgFullRequest, flagSeq, serialJSON, 1, payload)
	if !bytes.Equal(got[:8], want[:8]) {
		t.Errorf("request head % x, want % x", got[:8], want[:8])
	}
	if n := binary.BigEndian.Uint32(got[8:12]); int(n) != len(got)-12 {
		t.Errorf("size field %d, payload %d bytes", n, len(got)-12)
	}
	if !bytes.Equal(gunzip(t, got[12:]), payload) {
		t.Error("request payload differs after gunzip")
	}
	for i, c := range []struct {
		flags byte
		seq   int32
	}{{flagSeq, 3}, {flagSeq | flagLast, -11}} {
		head := unhex(t, f.AudioHeads[i])
		got := frame(msgAudio, c.flags, serialNone, c.seq, make([]byte, doubaoPacket))
		if !bytes.Equal(got[:8], head[:8]) {
			t.Errorf("audio seq %d head % x, want % x", c.seq, got[:8], head[:8])
		}
	}
}

func TestDoubaoParseReply(t *testing.T) {
	f := loadFrames(t)
	var texts []string
	for i, s := range f.Server {
		r, err := parseReply(unhex(t, s))
		if err != nil {
			t.Fatalf("frame %d: %v", i, err)
		}
		if r.Code != 0 {
			t.Errorf("frame %d: code %d", i, r.Code)
		}
		if want := i == len(f.Server)-1; r.Last != want {
			t.Errorf("frame %d: last %v, want %v", i, r.Last, want)
		}
		var b result
		if err := json.Unmarshal(r.Body, &b); err != nil {
			t.Fatalf("frame %d: %v", i, err)
		}
		texts = append(texts, b.Result.Text)
	}
	if want := []string{"", "three", "three barges passed", "Three barges passed at dusk."}; strings.Join(texts, "|") != strings.Join(want, "|") {
		t.Errorf("texts %q, want %q", texts, want)
	}

	r, err := parseReply(unhex(t, f.Error))
	if err != nil {
		t.Fatal(err)
	}
	var se ServerError
	if !errors.As(r.err(), &se) || se.Code != 45000001 || !strings.Contains(se.Msg, "11025 Hz") {
		t.Errorf("error frame: %v", r.err())
	}

	for _, bad := range [][]byte{nil, {0x11, 0x91}, {0x11, 0x91, 0x10, 0x00, 0, 0, 0, 1, 0, 0, 0, 9, '{'}} {
		if _, err := parseReply(bad); err == nil {
			t.Errorf("% x: no error", bad)
		}
	}
}

func TestDoubaoRequest(t *testing.T) {
	d := &Doubao{TwoPass: true, Hotwords: func() []string { return []string{"Okapi", "Quasar"} }}
	var req struct {
		Audio   map[string]any `json:"audio"`
		Request struct {
			Nonstream bool `json:"enable_nonstream"`
			DDC       bool `json:"enable_ddc"`
			Corpus    struct {
				Context string `json:"context"`
			} `json:"corpus"`
		} `json:"request"`
	}
	if err := json.Unmarshal(d.request(), &req); err != nil {
		t.Fatal(err)
	}
	if !req.Request.Nonstream || req.Request.DDC || req.Audio["rate"] != float64(16000) || req.Audio["format"] != "pcm" {
		t.Errorf("request %+v", req)
	}
	if want := `{"hotwords":[{"word":"Okapi"},{"word":"Quasar"}]}`; req.Request.Corpus.Context != want {
		t.Errorf("corpus.context %s, want %s", req.Request.Corpus.Context, want)
	}
	var shows struct {
		Request struct {
			Utterances bool `json:"show_utterances"`
		} `json:"request"`
	}
	if json.Unmarshal(d.request(), &shows); !shows.Request.Utterances {
		t.Error("show_utterances is off: the reply would carry no word times")
	}
}

// With show_utterances the reply carries each sentence's words and when
// they were said, in ms from the start of the audio, as the plan endpoint
// answered a synthesised clip: a Han character is a word, and a space
// between words comes as a word of its own with -1 times, which is left
// out. The stream keeps the words of the text it returns; a failed one has
// none.
func TestDoubaoWords(t *testing.T) {
	body := `{"audio_info":{"duration":2900},"result":{"text":"周四的 sync 挪到3:30。","utterances":[{"definite":true,"start_time":80,"end_time":2900,` +
		`"text":"周四的 sync 挪到3:30。","words":[{"text":"周","start_time":80,"end_time":280},{"text":"四","start_time":280,"end_time":480},` +
		`{"text":"的","start_time":480,"end_time":680},{"text":" ","start_time":-1,"end_time":-1},{"text":"sync","start_time":800,"end_time":1160},` +
		`{"text":" ","start_time":-1,"end_time":-1},{"text":"挪","start_time":1300,"end_time":1500},{"text":"到","start_time":1500,"end_time":1700},` +
		`{"text":"3:30","start_time":1700,"end_time":2400}]}]}}`
	want := []Word{{"周", 80, 280}, {"四", 280, 480}, {"的", 480, 680}, {"sync", 800, 1160}, {"挪", 1300, 1500}, {"到", 1500, 1700}, {"3:30", 1700, 2400}}
	f := loadFrames(t)
	f.Server = []string{f.Server[0], hex.EncodeToString(frame(msgFullResponse, flagSeq|flagLast, serialJSON, -2, []byte(body)))}
	p, d := newPlanWith(t, f, false)
	st := d.Open()
	st.Write(make([]int16, 1600))
	text, err := st.Finish(context.Background())
	<-p.done
	if err != nil || text != "周四的 sync 挪到3:30。" {
		t.Fatalf("Finish: %q, %v", text, err)
	}
	if got := st.(Timed).Words(); fmt.Sprint(got) != fmt.Sprint(want) {
		t.Errorf("words %v, want %v", got, want)
	}

	p, d = newPlan(t, true)
	st = d.Open()
	st.Write(make([]int16, 1600))
	if _, err := st.Finish(context.Background()); err == nil || st.(Timed).Words() != nil {
		t.Errorf("a failed stream: %v, words %v", err, st.(Timed).Words())
	}
	<-p.done
}

// planServer stands in for the plan endpoint. It keeps the upgrade
// headers, checks that the first frame is a full request with sequence 1,
// logs sequence and unpacked size of every audio packet up to the flagged
// last one, then replies with the fixture's frames — or its error frame
// when fail is set.
type planServer struct {
	t      *testing.T
	f      frames
	fail   bool
	seqs   []int32
	sizes  []int
	header http.Header
	done   chan struct{}
}

func (p *planServer) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	defer close(p.done)
	p.header = r.Header.Clone()
	c, err := websocket.Accept(w, r, nil)
	if err != nil {
		p.t.Error(err)
		return
	}
	defer c.CloseNow()
	c.SetReadLimit(-1)
	ctx := r.Context()
	_, msg, err := c.Read(ctx)
	if err != nil {
		p.t.Error(err)
		return
	}
	if msg[1]>>4 != msgFullRequest || binary.BigEndian.Uint32(msg[4:]) != 1 {
		p.t.Errorf("first frame % x", msg[:8])
	}
	c.Write(ctx, websocket.MessageBinary, unhex(p.t, p.f.Server[0]))
	for {
		_, msg, err := c.Read(ctx)
		if err != nil {
			p.t.Error(err)
			return
		}
		p.seqs = append(p.seqs, int32(binary.BigEndian.Uint32(msg[4:])))
		p.sizes = append(p.sizes, len(gunzip(p.t, msg[12:])))
		if msg[1]&flagLast != 0 {
			break
		}
	}
	if p.fail {
		c.Write(ctx, websocket.MessageBinary, unhex(p.t, p.f.Error))
		return
	}
	for _, s := range p.f.Server[1:] {
		c.Write(ctx, websocket.MessageBinary, unhex(p.t, s))
	}
	c.Read(ctx) // until the client closes
}

func newPlan(t *testing.T, fail bool) (*planServer, *Doubao) {
	return newPlanWith(t, loadFrames(t), fail)
}

// newPlanWith is newPlan replying with the frames f.
func newPlanWith(t *testing.T, f frames, fail bool) (*planServer, *Doubao) {
	p := &planServer{t: t, f: f, fail: fail, done: make(chan struct{})}
	srv := httptest.NewServer(p)
	t.Cleanup(srv.Close)
	d := &Doubao{URL: "ws" + strings.TrimPrefix(srv.URL, "http"), ResourceID: "volc.seedasr.sauc.duration",
		Key: func() (string, error) { return "k-test", nil }, TwoPass: true, Timeout: 5 * time.Second}
	return p, d
}

func TestDoubaoStream(t *testing.T) {
	p, d := newPlan(t, false)
	st := d.Open()
	block := make([]int16, 1600) // 100 ms, as the array delivers
	for range 17 {
		st.Write(block)
	}
	text, err := st.Finish(context.Background())
	if err != nil || text != "Three barges passed at dusk." {
		t.Fatalf("Finish: %q, %v", text, err)
	}
	<-p.done
	if p.header.Get("X-Api-Key") != "k-test" || p.header.Get("X-Api-Resource-Id") != "volc.seedasr.sauc.duration" ||
		p.header.Get("X-Api-Connect-Id") == "" {
		t.Errorf("headers %v", p.header)
	}
	// 1.7 s: eight 200 ms packets, seq 2…9, then the held-back 100 ms tail
	// as the last packet, seq -10
	var total int
	for i, s := range p.seqs {
		want := int32(i + 2)
		if i == len(p.seqs)-1 {
			want = -want
		}
		if s != want {
			t.Errorf("packet %d: seq %d, want %d", i, s, want)
		}
		total += p.sizes[i]
	}
	if total != 17*1600*2 || p.sizes[len(p.sizes)-1] == 0 {
		t.Errorf("sizes %v: %d bytes, want %d with audio in the last", p.sizes, total, 17*1600*2)
	}
}

func TestDoubaoStreamFailures(t *testing.T) {
	t.Run("server error", func(t *testing.T) {
		_, d := newPlan(t, true)
		st := d.Open()
		st.Write(make([]int16, 8000))
		_, err := st.Finish(context.Background())
		var se ServerError
		if !errors.As(err, &se) || se.Code != 45000001 {
			t.Errorf("Finish: %v, want code 45000001", err)
		}
	})
	t.Run("no server", func(t *testing.T) {
		srv := httptest.NewServer(http.NotFoundHandler())
		url := "ws" + strings.TrimPrefix(srv.URL, "http")
		srv.Close()
		d := &Doubao{URL: url, Key: func() (string, error) { return "k", nil }, Timeout: 5 * time.Second}
		st := d.Open()
		st.Write(make([]int16, 8000))
		t0 := time.Now()
		if _, err := st.Finish(context.Background()); err == nil || time.Since(t0) > 2*time.Second {
			t.Errorf("Finish: %v after %v, want a connect error at once", err, time.Since(t0))
		}
	})
	t.Run("no key", func(t *testing.T) {
		d := &Doubao{URL: "ws://127.0.0.1:1", Key: func() (string, error) { return "", errors.New("no key file") }}
		st := d.Open()
		if _, err := st.Finish(context.Background()); err == nil || !strings.Contains(err.Error(), "no key file") {
			t.Errorf("Finish: %v", err)
		}
	})
	t.Run("silent server", func(t *testing.T) {
		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			c, _ := websocket.Accept(w, r, nil)
			defer c.CloseNow()
			for {
				if _, _, err := c.Read(r.Context()); err != nil {
					return
				}
			}
		}))
		t.Cleanup(srv.Close)
		d := &Doubao{URL: "ws" + strings.TrimPrefix(srv.URL, "http"), Key: func() (string, error) { return "k", nil }, Timeout: 300 * time.Millisecond}
		st := d.Open()
		st.Write(make([]int16, 8000))
		if _, err := st.Finish(context.Background()); err == nil || !strings.Contains(err.Error(), "no final text") {
			t.Errorf("Finish: %v", err)
		}
	})
}
